# Generated by Django 4.1.2 on 2022-10-23 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blogs', '0001_initial'),
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blogs.blog')),
                ('tag_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tags.tag')),
            ],
        ),
    ]
