# Generated by Django 4.1.2 on 2022-11-24 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_blog_created_at'),
        ('tagBlogs', '0003_alter_tagblog_blog_id_alter_tagblog_tag_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagblog',
            name='blog_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.blog'),
        ),
    ]
