# Generated by Django 4.1.2 on 2022-11-16 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='date_posted',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='likes',
        ),
    ]
